USE ROLE accountadmin;

SELECT SYSTEM$DISABLE_SNOWFLAKE_LEARNING_ENVIRONMENT();

CREATE DATABASE SNOWFLAKE_LEARNING_DB;

CREATE ROLE SNOWFLAKE_LEARNING_ROLE;

GRANT ROLE SNOWFLAKE_LEARNING_ROLE TO ROLE PUBLIC;

CREATE WAREHOUSE SNOWFLAKE_LEARNING_WH
  COMMENT = 'Warehouse used for executing template and demo content'
  WAREHOUSE_SIZE = 'X-Small'
  AUTO_RESUME = true
  AUTO_SUSPEND = 300;

GRANT USAGE, MONITOR, OPERATE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE SNOWFLAKE_LEARNING_ROLE;

GRANT USAGE ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE SNOWFLAKE_LEARNING_ROLE;

GRANT CREATE SCHEMA ON DATABASE SNOWFLAKE_LEARNING_DB TO ROLE SNOWFLAKE_LEARNING_ROLE;

-- 초기화
USE ROLE ACCOUNTADMIN;
SELECT SYSTEM$DISABLE_SNOWFLAKE_LEARNING_ENVIRONMENT();

-- DATABASE
SHOW DATABASES LIKE 'SNOWFLAKE_LEARNING_DB';
DROP DATABASE SNOWFLAKE_LEARNING_DB;

-- WAREHOUSE
SHOW WAREHOUSES LIKE 'SNOWFLAKE_LEARNING_WH';
DROP WAREHOUSE SNOWFLAKE_LEARNING_WH;

-- ROLE
SHOW ROLES LIKE 'SNOWFLAKE_LEARNING_ROLE';
DROP ROLE SNOWFLAKE_LEARNING_ROLE;
